# Generated by Django 5.2.4 on 2025-07-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_recruiter_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='type',
        ),
        migrations.AddField(
            model_name='recruiter',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default='2025-07-28 12:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recruiter',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recruiter_images/'),
        ),
    ]
