# Generated by Django 5.2.4 on 2025-08-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_remove_recruiter_company_name_remove_recruiter_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
